/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MajdyModels (https://sketchfab.com/MG990)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iphone-17-pro-max-87fc1df741384124a8ce0226d2b2058d
Title: iPhone 17 Pro Max
*/

import { useGLTF } from "@react-three/drei";

export function IPhone17ProMax(props) {
  const { nodes, materials } = useGLTF("/iphone_17_pro_max.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube010_black002_0.geometry}
            material={materials["black.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube010_basecolor001_0.geometry}
            material={materials["basecolor.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube010_metalframe002_0.geometry}
            material={materials["metalframe.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube010_metaL001_0.geometry}
            material={materials["metaL.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube010_glass002_0.geometry}
            material={materials["glass.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube010_screen001_0.geometry}
            material={materials["screen.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube010_Material005_0.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube010_Material006_0.geometry}
            material={materials["Material.006"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube010_Material007_0.geometry}
            material={materials["Material.007"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube010_gray001_0.geometry}
            material={materials["gray.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube010_backpanel001_0.geometry}
            material={materials["backpanel.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube010_lensinglass_0.geometry}
            material={materials.lensinglass}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/iphone_17_pro_max.glb");
