import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { CartProvider } from "@/context/CartContext";
import UserRoleProvider from "@/context/UserRoleContext";
import { getUserRole } from "@/lib/supabase/server-role";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const role = await getUserRole();

  return (
    <html
      lang="en"
      className={cn(
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
      )}>
      <body className="min-h-full bg-zinc-50 selection:bg-sky-700/80 selection:text-cyan-300">
        <div className="w-[90%] max-w-7xl mx-auto">
          <UserRoleProvider role={role}>
            <CartProvider>{children}</CartProvider>
          </UserRoleProvider>
        </div>
      </body>
    </html>
  );
}
